application: geoyagur
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:


- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/js
  static_dir: static/js

- url: /static/css
  static_dir: static/css



